spring:
  profiles:
    active:
      - EN
      - cat
bht:
  username: bountyHunter
  password: bhtPassword
  jdbcUrl: bhtUrl

---
spring:
  profiles: prod
bht:
  username: prodBountyHunter
  password: prodBhtPassword
  jdbcUrl: prodBhtUrl
